server:
  port: 8080
  context-path: /api-mock

runtime: java
env: flex

handlers:
- url: /.*
  script: this field is required, but ignored
  secure: always  # Require HTTPS

manual_scaling:
  instances: 1