/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'KXP8101' at '10/7/16 12:14 PM' with Gradle 2.14.1
 *
 * @author KXP8101, @date 10/7/16 12:14 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
